language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
# deploy:
#   provider: npm
#   skip_cleanup: true
#   email: $EMAIL
#   api_key: $NPM_TOKEN
#   on:
#     branch: master